# Generated by Django 3.2.12 on 2024-07-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='img',
            field=models.ImageField(default=1, upload_to='banners/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='generate_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
