# Generated by Django 3.2.12 on 2024-07-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0003_auto_20240729_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='generate_code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='generate_code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='generate_code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='generate_code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='productimg',
            name='generate_code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='generate_code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
